name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set environment variable
      run: echo "MY_ENV_VAR=HelloWorld" >> $GITHUB_ENV

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Run JavaScript
      run: node script.js
      env:
        MY_ENV_VAR: ${{ env.MY_ENV_VAR }}
