name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Decrypt test.json.gpg
      id: decrypt
      run: |
        DECRYPTED_JSON=$(gpg --quiet --batch --yes --decrypt --passphrase="$LARGE_SECRET_PASSPHRASE" --output - test.json.gpg)
        echo "::set-output name=decrypted_json::$DECRYPTED_JSON"
      env:
        LARGE_SECRET_PASSPHRASE: ${{ secrets.LARGE_SECRET_PASSPHRASE }}

    - name: Create public directory
      run: mkdir -p public

    - name: Embed JSON Data into HTML
      run: |
        echo "<script>const jsonData = ${{ steps.decrypt.outputs.decrypted_json }};</script>" > public/json-data.js
      shell: bash

    - name: Verify public/json-data.js content
      run: cat public/json-data.js

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add public/json-data.js
        git commit -m "Embed decrypted JSON data into HTML"
        git push
